/*
 * Copyright © 2026 Plasticity.Cloud Limited & CoDriverLabs Limited. All rights reserved.
 */
package ai.codriverlabs.scaleoutbuild.planner;

/**
 * How a plan supplies the native-image argument file.
 *
 * <p>Describes the <em>mechanism</em>, not the framework. The values were previously named
 * {@code QUARKUS_NATIVE_SOURCES} and {@code DERIVED}, which read as a framework list and became actively
 * misleading once Spring Boot's argfile started being rewritten: it is generated by us, but it is nothing to
 * do with {@link DerivedClasspathStrategy}. Two frameworks can share a mechanism, and one framework can
 * change mechanism, so the distinction that matters to the staging code is only whether the argfile is
 * already among the staged files or has to be written.
 */
public enum InputMode {

    /** The argfile is staged verbatim from the project, as Quarkus's relocatable {@code native-sources}. */
    STAGED_ARGS_FILE,

    /** The argfile content is produced by this plugin, from a rewrite or from the resolved classpath. */
    GENERATED_ARGS_FILE
}
