/*
 * Copyright © 2026 Plasticity.Cloud Limited & CoDriverLabs Limited. All rights reserved.
 */
package ai.codriverlabs.scaleoutbuild.planner;

import ai.codriverlabs.scaleoutbuild.build.StagingLayout;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * Everything needed to stage one project's native-image build inputs.
 *
 * <p>Both input modes reduce to the same shape — a list of files with their destination paths, plus
 * optionally the text of a generated argfile — so the staging code has a single path regardless of
 * whether Quarkus produced the arguments or we derived them.
 */
public final class NativeImageInputPlan {

    private final InputMode mode;
    private final List<StagedFile> files;
    private final String argsFileName;
    private final String generatedArgsContent;
    private final List<String> expectedArtifacts;

    private NativeImageInputPlan(InputMode mode, List<StagedFile> files, String argsFileName,
                                 String generatedArgsContent, List<String> expectedArtifacts) {
        this.mode = Objects.requireNonNull(mode, "mode");
        this.files = List.copyOf(files);
        this.argsFileName = Objects.requireNonNull(argsFileName, "argsFileName");
        this.generatedArgsContent = generatedArgsContent;
        this.expectedArtifacts = List.copyOf(expectedArtifacts);
    }

    /**
     * Plan that reuses a generated argfile already present among the staged files.
     */
    public static NativeImageInputPlan passThrough(List<StagedFile> files, String argsFileName,
                                                   List<String> expectedArtifacts) {
        if (files.stream().noneMatch(file -> file.relativePath().equals(argsFileName))) {
            throw new IllegalArgumentException(
                    "Pass-through plan must stage its argfile '" + argsFileName + "'");
        }
        return new NativeImageInputPlan(InputMode.STAGED_ARGS_FILE, files, argsFileName, null,
                expectedArtifacts);
    }

    /**
     * Plan whose argfile is generated by the plugin and written during staging.
     */
    public static NativeImageInputPlan generated(List<StagedFile> files, String argsFileContent,
                                                 List<String> expectedArtifacts) {
        Objects.requireNonNull(argsFileContent, "argsFileContent");
        return new NativeImageInputPlan(InputMode.GENERATED_ARGS_FILE, files,
                StagingLayout.DEFAULT_ARGS_FILE_NAME, argsFileContent, expectedArtifacts);
    }

    public InputMode mode() {
        return mode;
    }

    /** Files to place in the staging area, destination paths relative to the staging root. */
    public List<StagedFile> files() {
        return files;
    }

    /** Name of the argfile inside the staging root. */
    public String argsFileName() {
        return argsFileName;
    }

    /** Argfile text to write, empty when the argfile is staged as a file instead. */
    public Optional<String> generatedArgsContent() {
        return Optional.ofNullable(generatedArgsContent);
    }

    /**
     * Binary names the build should produce. Empty means "discover by scanning", which is the normal
     * case for a pass-through argfile that names its own output.
     */
    public List<String> expectedArtifacts() {
        return expectedArtifacts;
    }

    /** Total bytes to be staged, useful for reporting how much a first upload will cost. */
    public long totalBytes() {
        return files.stream().mapToLong(file -> file.source().toFile().length()).sum();
    }

    @Override
    public String toString() {
        return "NativeImageInputPlan{mode=" + mode
                + ", files=" + files.size()
                + ", argsFileName=" + argsFileName
                + ", expectedArtifacts=" + expectedArtifacts
                + '}';
    }
}
